### PR TITLE
Travis migration to Github Actions

### PR DESCRIPTION
**Pull request by glauesppen**
Hi all,

I build a github actions file to migrate from Travis. This script validates the PR open to merge into main branch and the pushes into main branch. We can extend it to other branches if needed.

There is a few questions I want to discuss with you all before we merge this PR:
- I saw we are using a ./script/cibuild file to update the jekyll. What do you think about putting those commands directly in the actions script?
- I inserted a release changelog plugin into the actions script. What do you think about using it to log our releases in prod? Here is the docs: https://github.com/marketplace/actions/release-changelog-builder

Let me know your thoughts :)

### CODE REVIEW

**Comment by JorgeQuiane** [comment]
Hi all,

- I don't see any issue in having cibuild's commands in the action script, so I vote for doing so. This would be more transparent for everyone IMO.
- +1 for also having the release changelog in the action script :)

Best!

**Comment by 2pk03** [comment]
+1, if no objections in the next 48h I'm going to merge.

**Comment by glauesppen** [comment]
I am changing the approach to the release creator, since apache only allows verified github actions on the marketplace

**Comment by 2pk03** [comment]
Sure, than we wait with the merge.

**Comment by 2pk03** [comment]
Thank you, I'm going and merge this PR! Congratulations on your first commit to Wayang!

**Pull request merged**
